import { useState } from 'react'
import { award, schedule } from './data/equity'
import { estimatedValue, money, number, remainingEvents } from './lib/equity'

const nav = ['Overview', 'My grants', 'Vesting schedule', 'Transactions']
const stats = [{ label: 'Total granted', key: 'granted' }, { label: 'Vested', key: 'vested' }, { label: 'Unvested', key: 'unvested' }, { label: 'Available', key: 'available' }, { label: 'Sold', key: 'sold' }] as const
const formatDate = (date: string) => new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${date}T00:00:00Z`))

function Sidebar({ active, onSelect }: { active: string; onSelect: (item: string) => void }) {
  return <aside className="sidebar"><div className="brand"><span className="brand-mark">S</span><span>Seoul Equity</span></div><div className="profile"><div className="avatar">AK</div><div><b>Alex Kim</b><small>Demo employee</small></div></div><nav aria-label="Main navigation">{nav.map((item) => <button className={active === item ? 'nav-item active' : 'nav-item'} key={item} onClick={() => onSelect(item)}>{item}</button>)}</nav><p className="sidebar-foot">Fictional account<br />For demonstration only</p></aside>
}

function Summary({ price }: { price: number }) {
  const pct = (award.vested / award.granted) * 100
  return <section className="summary card"><div className="summary-top"><div><span className="eyebrow">AWARD SUMMARY</span><h2>{award.id}</h2><p>{award.type} · Granted {formatDate(award.grantDate)}</p></div><div className="grant-total"><strong>{number(award.granted)}</strong><span>RSUs granted</span></div></div><div className="progress-copy"><span><b>{pct}%</b> vested</span><span><b>{100 - pct}%</b> unvested</span></div><div className="progress" aria-label={`${pct}% vested`}><span style={{ width: `${pct}%` }} /></div><div className="progress-caption"><span>{number(award.vested)} vested</span><span>{number(award.unvested)} remaining</span></div><div className="estimated"><div><span>Vested estimated value</span><strong>{money(estimatedValue(award.vested, price))}</strong></div><div><span>Unvested estimated value</span><strong>{money(estimatedValue(award.unvested, price))}</strong></div><p>Illustrative price: <b>{money(price)}</b> per share</p></div></section>
}

function Upcoming() { const upcoming = remainingEvents(schedule); return <section className="upcoming card"><div className="section-heading"><div><span className="eyebrow">NEXT MILESTONE</span><h2>Upcoming vesting</h2></div><span className="calendar">◷</span></div><div className="next-date">{formatDate(upcoming[0].date)}</div><strong>{number(upcoming[0].quantity)} RSUs</strong><p>will become available to you.</p><div className="timeline">{upcoming.map((event, index) => <div className="timeline-row" key={event.date}><i /><div><b>{index === 0 ? 'Next' : 'Final'} vest</b><span>{formatDate(event.date)}</span></div><strong>{number(event.quantity)}</strong></div>)}</div><button className="text-button">View full schedule →</button></section> }

function DataTable() { return <section className="table-section card"><div className="section-heading"><div><span className="eyebrow">YOUR EQUITY</span><h2>Grant details</h2></div><button className="text-button">Award details →</button></div><div className="table-scroll"><table><thead><tr><th>Grant</th><th>Grant date</th><th>Quantity</th><th>Status</th><th>Estimated value</th></tr></thead><tbody><tr><td><b>{award.id}</b><span>{award.type}</span></td><td>{formatDate(award.grantDate)}</td><td>{number(award.granted)}</td><td><em>Active</em></td><td>{money(estimatedValue(award.granted, award.sharePrice))}</td></tr></tbody></table></div></section> }

function Schedule() { return <section className="schedule card"><div className="section-heading"><div><span className="eyebrow">4-YEAR VESTING TERM</span><h2>Vesting schedule</h2></div><span className="asof">As of {formatDate(award.asOf)}</span></div>{schedule.map((event) => <div className="schedule-row" key={event.date}><span className={`dot ${event.status.toLowerCase()}`} /><div><b>{formatDate(event.date)}</b><small>{event.status}</small></div><strong>{number(event.quantity)} RSUs</strong><span className={event.status === 'Vested' ? 'status vested' : 'status'}>{event.status}</span></div>)}</section> }

function App() { const [active, setActive] = useState('Overview'); const [price, setPrice] = useState<number>(award.sharePrice); return <div className="app"><Sidebar active={active} onSelect={setActive} /><main><header><div><p className="greeting">Good morning, Alex</p><h1>Equity overview</h1><p className="subtitle">A clear view of your fictional RSU award.</p></div><label className="price-input">Mock share price <div><span>$</span><input aria-label="Mock share price" type="number" min="0" step="0.5" value={price} onChange={(event) => setPrice(Number(event.target.value))} /></div></label></header><div className="disclaimer" role="note">Demo account — All values are fictional mock data and are not financial or tax advice.</div><div className="main-grid"><Summary price={price} /><Upcoming /></div><section className="stats" aria-label="Award totals">{stats.map(({ label, key }) => <article className="stat card" key={key}><span>{label}</span><strong>{number(award[key])}</strong><small>RSUs</small></article>)}</section><div className="lower-grid"><DataTable /><Schedule /></div><section className="transactions card"><span className="eyebrow">ACTIVITY</span><h2>Transaction history</h2><p>No sales or transactions yet for this award.</p></section></main></div> }
export default App
